// ─── js/data.js ──────────────────────────────────────────────────────────────

const PIN_CATEGORIES = [
  { id:"hospedagem",  label:"🛏️ Hospedagem",       cls:"cat-hospedagem",  color:"#1D4ED8" },
  { id:"turistico",   label:"🏛️ Ponto Turístico",   cls:"cat-turistico",   color:"#7E22CE" },
  { id:"passeio",     label:"🎯 Passeio",            cls:"cat-passeio",     color:"#15803D" },
  { id:"apoio",       label:"🏙️ Cidade de Apoio",    cls:"cat-apoio",       color:"#C2410C" },
  { id:"carro",       label:"🚗 Locação de Carro",   cls:"cat-carro",       color:"#0369A1" },
  { id:"posto",       label:"⛽ Posto / Serviço",    cls:"cat-posto",       color:"#A16207" },
  { id:"restaurante", label:"🍽️ Restaurante",         cls:"cat-restaurante", color:"#BE123C" },
  { id:"camping",     label:"🏕️ Camping",             cls:"cat-camping",     color:"#3F6212" },
  { id:"mirante",     label:"🌄 Mirante / Vista",    cls:"cat-mirante",     color:"#B45309" },
  { id:"fronteira",   label:"🛂 Fronteira / Balsa",  cls:"cat-fronteira",   color:"#475569" },
];

const REGION_COLORS = {
  "Ruta 40":           "#8B6914",
  "Carretera Austral": "#1B6B3A",
  "Ruta 40 / Chaltén": "#4A7C59",
  "Torres del Paine":  "#C0392B",
  "Punta Arenas":      "#2471A3",
  "Terra do Fogo":     "#1A5276",
  "Ushuaia":           "#0E6655",
  "Retorno":           "#5D6D7E",
};

const RESERVAS = [
  { id:"r1",  text:"🧊 Navegação Laguna San Rafael (Turismo Exploradores)",      urgency:"🔴 Urgente" },
  { id:"r2",  text:"🏕️ Camping Río Serrano – Natal (cajalosandes.cl)",           urgency:"🔴 Urgente" },
  { id:"r3",  text:"🏔️ Torres del Paine – entrada e camping W",                  urgency:"🔴 Urgente" },
  { id:"r4",  text:"✈️ Voo Punta Arenas → Bariloche (LATAM/Aerolíneas)",         urgency:"🔴 Urgente" },
  { id:"r5",  text:"📄 Autorização carro para múltiplas travessias ARG/CHI",     urgency:"🔴 Urgente" },
  { id:"r6",  text:"🌋 Seguro viagem internacional",                              urgency:"🔴 Urgente" },
  { id:"r7",  text:"⛴️ Balsa Punta Arenas → Porvenir",                           urgency:"🟡 Antes de nov" },
  { id:"r8",  text:"🐧 Barco Isla Magdalena – pinguins (Turismo Comapa)",        urgency:"🟡 Antes de nov" },
  { id:"r9",  text:"🏨 Hospedagem El Chaltén (20-22/12)",                        urgency:"🟡 Antes de nov" },
  { id:"r10", text:"🏨 Hospedagem El Calafate (22-23/12)",                       urgency:"🟡 Antes de nov" },
  { id:"r11", text:"🛥️ Navegação Canal Beagle – Ushuaia",                        urgency:"🟢 Até out" },
  { id:"r12", text:"🍽️ Jantar de Réveillon em Ushuaia (31/12)",                  urgency:"🟢 Até out" },
  { id:"r13", text:"🧊 Passarelas Glaciar Perito Moreno – entrada parque",       urgency:"🟢 Até out" },
];

const DEFAULT_DAYS = [
  { id:1,  date:"16/12", emoji:"🚗", title:"Bariloche → Perito Moreno (ARG)",                  region:"Ruta 40",           drive:"~800 km",         stays:"Perito Moreno (ARG)",        lat:-46.4333, lng:-70.9333, highlights:["Dia de estrada pela Ruta 40","Abastecer em Bariloche antes de sair","Paisagem de estepe patagônica"], tip:"Saída bem cedo — dia mais puxado em km. Ótimo para audiobooks.", paleo:null, alert:null },
  { id:2,  date:"17/12", emoji:"🌊", title:"Perito Moreno → Chile Chico → Río Tranquilo",      region:"Carretera Austral",  drive:"~5h + fronteira",  stays:"Puerto Río Tranquilo (CHI)", lat:-46.6167, lng:-72.6667, highlights:["Cruzar fronteira ARG→CHI em Los Antiguos / Chile Chico","Contornar o Lago General Carrera – um dos maiores da América do Sul","Estrada mais cênica e sinuosa da Patagônia","Capelas de Mármore ao entardecer (~$15 USD por barco)"], tip:"Chegar antes das 17h para o barco das Capelas.", paleo:null, alert:null },
  { id:3,  date:"18/12", emoji:"🧊", title:"Expedição Laguna San Rafael",                      region:"Carretera Austral",  drive:"Dia de barco",     stays:"Puerto Río Tranquilo (CHI)", lat:-46.6333, lng:-73.8833, highlights:["Valle Exploradores – estrada entre geleiras e cachoeiras","Navegação pelos fiordes até o Glaciar San Rafael","Icebergs flutuando na laguna","Campo de Gelo Norte: ~4.200 km²"], tip:null, paleo:"🧊 Campo de Gelo Norte: relíquia da última glaciação. San Rafael é um dos glaciares mais acessíveis desse sistema.", alert:"⚠️ RESERVAR COM MESES DE ANTECEDÊNCIA. Operadoras: Turismo Exploradores ou Destino Patagonia." },
  { id:4,  date:"19/12", emoji:"🛤️", title:"Río Tranquilo → Chile Chico → Gobernador Gregores",region:"Ruta 40",           drive:"~480 km + front.",  stays:"Gobernador Gregores (ARG)", lat:-48.7667, lng:-70.25,   highlights:["Retorno contornando o Lago General Carrera","Cruzar CHI→ARG em Chile Chico","Trechos de rípio (cascalho) na Ruta 40"], tip:"Pneu reserva em boas condições para o rípio.", paleo:null, alert:"⚠️ Confirmar com locadora autorização para múltiplas travessias ARG/CHI." },
  { id:5,  date:"20/12", emoji:"🏔️", title:"Gobernador Gregores → El Chaltén",                region:"Ruta 40 / Chaltén",  drive:"~300 km",          stays:"El Chaltén (ARG)",          lat:-49.3333, lng:-72.8833, highlights:["Trecho mais curto após sequência de estrada","Chegada ao pé do Monte Fitz Roy","Mirador de los Cóndores (trilha leve de 1h)","El Chaltén tem ótimas cervejarias artesanais"], tip:"Descansar e aclimatar para a trilha grande do dia seguinte.", paleo:null, alert:null },
  { id:6,  date:"21/12", emoji:"🗻", title:"El Chaltén — Laguna de los Tres (Fitz Roy)",       region:"Ruta 40 / Chaltén",  drive:"Dia de trilha",    stays:"El Chaltén (ARG)",          lat:-49.3167, lng:-72.9667, highlights:["Trilha Laguna de los Tres — 21km, ~8h, 800m de desnível","Vista do Fitz Roy refletido na laguna turquesa","Laguna Sucia (opcional na volta)","Uma das trilhas mais icônicas da América do Sul"], tip:"Sair às 6h. Levar marmita e roupa de vento — a laguna é muito exposta.", paleo:null, alert:null },
  { id:7,  date:"22/12", emoji:"🧊", title:"El Chaltén → El Calafate → Glaciar Perito Moreno", region:"Ruta 40 / Chaltén",  drive:"~210 km",          stays:"El Calafate (ARG)",         lat:-50.3375, lng:-72.2648, highlights:["Deslocamento curto pela manhã (~3h)","Passarelas do Glaciar Perito Moreno à tarde","Um dos poucos glaciares que ainda avança no mundo","Estrondos das placas de gelo caindo na água"], tip:"Entrada no parque Los Glaciares ~$25 USD. Tarde suficiente para ver tudo.", paleo:"🧊 Perito Moreno avança ~2m por dia enquanto a maioria dos glaciares recua. Fenômeno geológico raro.", alert:null },
  { id:8,  date:"23/12", emoji:"🚗", title:"El Calafate → Torres del Paine (entrada)",         region:"Torres del Paine",   drive:"~3h + fronteira",  stays:"Camping Río Serrano (CHI) 🎄", lat:-51.2272, lng:-72.9716, highlights:["Cruzar ARG→CHI no passo Río Don Guillermo","Check-in no Camping Río Serrano","Primeiros avistamentos de guanacos e possível puma","Lago Sarmiento: estromatólitos vivos nas margens"], tip:"Chegar cedo para montar acampamento com luz do dia. Entrada do parque ~$35 USD por pessoa.", paleo:"🦠 Lago Sarmiento: estromatólitos de cianobactérias — estruturas que existem há bilhões de anos.", alert:"⚠️ Reservar Camping Río Serrano em cajalosandes.cl — lotado no Natal!" },
  { id:9,  date:"24/12", emoji:"🗻", title:"Torres del Paine — Base das Torres 🎄",             region:"Torres del Paine",   drive:"Dia de trilha",    stays:"Camping Río Serrano (CHI)", lat:-50.9422, lng:-72.9897, highlights:["Trilha Base das Torres — 19km, ~8h, a mais famosa do parque","Os três paredões de granito de 2.800m","Lago turquesa no sopé das torres","Véspera de Natal diante das torres!"], tip:"Sair às 5h30 para o nascer do sol nas torres. Ceia especial no camping à noite.", paleo:null, alert:null },
  { id:10, date:"25/12", emoji:"🎅", title:"Torres del Paine — Mirantes e Contemplação",       region:"Torres del Paine",   drive:"Passeios de carro", stays:"Camping Río Serrano (CHI)", lat:-51.05,   lng:-73.05,   highlights:["Circuito cênico de carro pelos mirantes","Salto Grande","Lago Pehoé com vista para os Cuernos del Paine","Lago Grey — icebergs flutuando na beira"], tip:"Serviços reduzidos no Natal. Levar tudo de comida e bebida para a ceia.", paleo:null, alert:null },
  { id:11, date:"26/12", emoji:"🐾", title:"Torres del Paine → Cueva do Milodón → Punta Arenas",region:"Torres del Paine",  drive:"~3h",              stays:"Punta Arenas (CHI)",        lat:-53.1548, lng:-70.9112, highlights:["Manhã livre: última contemplação ou trilha curta","Cueva del Milodón no caminho (2h de visita)","Chegada em Punta Arenas"], tip:"A Cueva fica no caminho — sem desvio extra.", paleo:"🦥 Cueva del Milodón: restos do Mylodon darwinii (preguiça-gigante de 3m) com pele e pelos preservados. Viveu até ~10.000 a.C.", alert:null },
  { id:12, date:"27/12", emoji:"🐧", title:"Punta Arenas — Isla Magdalena + Museu",             region:"Punta Arenas",       drive:"Barco ~2h30",      stays:"Punta Arenas (CHI)",        lat:-52.933,  lng:-70.767,  highlights:["Pengüinera Isla Magdalena — colônia de 60.000 pinguins-de-Magalhães","Museu Regional de Magallanes — fósseis e megafauna pleistocênica"], tip:"Reservar barco com antecedência: Turismo Comapa.", paleo:"🦴 Museu de Punta Arenas: fósseis de megafauna pleistocênica e história geológica da Patagônia.", alert:null },
  { id:13, date:"28/12", emoji:"⛴️", title:"Punta Arenas → Porvenir (balsa) → Ushuaia",        region:"Terra do Fogo",      drive:"Balsa 2h30 + 4h",  stays:"Ushuaia (ARG)",             lat:-54.8019, lng:-68.3029, highlights:["Balsa pelo Estreito de Magalhães até Porvenir","Terra do Fogo chilena — paisagem de turfa e estepe","Lago Fagnano: cortado pela Falha de Magalhães","Chegada a Ushuaia — cidade mais austral do mundo"], tip:"Reservar balsa com antecedência — cancela por vento forte.", paleo:"🌍 Falha de Magalhães: falha geológica ativa — o Lago Fagnano existe por causa dela.", alert:null },
  { id:14, date:"29/12", emoji:"🌲", title:"Ushuaia — Parque Nacional Tierra del Fuego",        region:"Ushuaia",            drive:"30 min do centro", stays:"Ushuaia (ARG)",             lat:-54.8667, lng:-68.6,    highlights:["Único parque nacional argentino com costa marítima","Trilhas pela floresta de lenga e orla do Canal Beagle","Castores invasores — impacto ecológico visível na floresta","Trem do Fim do Mundo (El Tren del Fin del Mundo)"], tip:"Trem de ida, trilha de volta. Dia inteiro no parque.", paleo:"🦫 Castores introduzidos em 1940 transformaram a floresta — caso clássico de espécie invasora.", alert:null },
  { id:15, date:"30/12", emoji:"🛥️", title:"Ushuaia — Navegação Canal Beagle",                  region:"Ushuaia",            drive:"Barco ~4h",        stays:"Ushuaia (ARG)",             lat:-54.87,   lng:-68.0,    highlights:["Ilhotas com leões-marinhos e lobos-marinhos","Pinguins de Magalhães e de penacho amarelo","Cormorões reais","O mesmo canal navegado por Darwin em 1832"], tip:"Contratar passeio pela manhã. Levar roupa de vento e câmera com teleobjetiva.", paleo:"🔬 Darwin navegou aqui em 1832 a bordo do HMS Beagle — observações que inspiraram A Origem das Espécies.", alert:null },
  { id:16, date:"31/12", emoji:"🎆", title:"Ushuaia — Réveillon no Fim do Mundo",               region:"Ushuaia",            drive:"—",                stays:"Ushuaia (ARG) 🎆",          lat:-54.8019, lng:-68.3029, highlights:["Glaciar Martial pela manhã — vista da cidade e do canal","Museu do Fim do Mundo","Réveillon com Canal Beagle ao fundo — frio e mágico!"], tip:"Reservar jantar com antecedência — restaurantes lotam no réveillon.", paleo:null, alert:null },
  { id:17, date:"01/01", emoji:"🥂", title:"Ushuaia — Descanso pós-réveillon",                  region:"Ushuaia",            drive:"—",                stays:"Ushuaia (ARG)",             lat:-54.8019, lng:-68.3029, highlights:["Dia livre e sem compromisso","Valle de los Lobos — trekking selvagem quase sem turistas","Compras e gastronomia local"], tip:"Recuperar energia. Dia perfeito para explorar sem pressa.", paleo:"👣 Povos Yaghan habitaram a Terra do Fogo por mais de 10.000 anos em condições extremas.", alert:null },
  { id:18, date:"02/01", emoji:"🏔️", title:"Ushuaia — Glaciar Martial + Lago Fagnano",         region:"Ushuaia",            drive:"1h até Fagnano",   stays:"Ushuaia (ARG)",             lat:-54.7833, lng:-68.55,   highlights:["Glaciar Martial pela manhã — caminhada urbana com vista panorâmica","Lago Fagnano (Kami) à tarde — 1h de Ushuaia pela Ruta 3","Paisagem de fim do mundo com neve nas montanhas"], tip:"Glaciar de manhã, lago de tarde. Dois destinos em um dia.", paleo:null, alert:null },
  { id:19, date:"03/01", emoji:"🛤️", title:"Ushuaia → Río Grande",                              region:"Terra do Fogo",      drive:"~3h",              stays:"Río Grande (ARG)",          lat:-53.7878, lng:-67.7069, highlights:["Estrada pela estepe fueguina","Arredores de Porvenir: fósseis marinhos do Mioceno (~15M anos)","Última noite na Terra do Fogo"], tip:"Río Grande é cidade de passagem — jantar e dormir.", paleo:"🐚 Fósseis de moluscos e baleias primitivas do Mioceno nos arredores de Porvenir.", alert:null },
  { id:20, date:"04/01", emoji:"⛴️", title:"Río Grande → Punta Arenas (via Chile)",             region:"Retorno",            drive:"~5h + balsa",      stays:"Punta Arenas (CHI)",        lat:-53.1548, lng:-70.9112, highlights:["Balsa de volta pelo Estreito de Magalhães","Último dia na Patagônia chilena","Dia de buffer — a Patagônia sempre surpreende com clima"], tip:"Usar como buffer. Se tudo correu bem, dia para compras e relaxar.", paleo:null, alert:null },
  { id:21, date:"05/01", emoji:"✈️", title:"Punta Arenas → Bariloche (voo)",                   region:"Retorno",            drive:"Voo",              stays:"Bariloche (ARG)",           lat:-41.1335, lng:-71.3103, highlights:["Voo Punta Arenas → Bariloche (LATAM ou Aerolíneas)","Devolução do carro em Bariloche","Evita 1.400km de volta pela Ruta 40"], tip:"Pesquisar em LATAM e Aerolíneas com antecedência.", paleo:null, alert:"⚠️ Comprar voo antecipado — pode esgotar na alta temporada." },
  { id:22, date:"06-12/01", emoji:"🏠", title:"Bariloche — Dias finais e buffer",               region:"Retorno",            drive:"—",                stays:"Bariloche (ARG)",           lat:-41.1335, lng:-71.3103, highlights:["Dias de descanso ou passeios em Bariloche","Rota dos 7 Lagos (opcional)","Voo de volta ao Brasil"], tip:"Bariloche em dezembro é linda — Nahuel Huapi, chocolate e cerveja artesanal.", paleo:null, alert:null },
];